# -*- coding: utf-8 -*-
"""Lab_report2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BwtV0eIwx_rKSEe7msi9DzGb-kXpX2Wv

In 8-puzzle:
```python
(1, 2, 3)
(4, 0, 5)
(6, 7, 8)
```
Here, 0 means blank space.
We move the blank space Up, Down, Left, or Right to reach the goal state:
```python
(1, 2, 3)
(4, 5, 6)
(7, 8, 0)
```

#Problem: State Mapping Problem: 8-Puzzle Problem using BFS

1. **deque** use kora hoy BFS er queue bananor jonno.
BFS always first inserted state first explore kore, tai queue dorkar.

Normal list use korleo hoto, but deque faster.

2. Goal Checking Function:
Ei function check kore current puzzle state goal state er same kina.
Example:
```python
state = (
    (1, 2, 3),
    (4, 5, 6),
    (7, 8, 0)
)
```
If this is same as goal, then solution found.

Simply, **is_goal() function** checks whether the current state is equal to the goal state. If equal, it returns True; otherwise, it returns False.

3. Blank Tile Finding Function:
i = row; j = column

for i,
Example:
```python
row 0 = (1, 2, 3)
row 1 = (4, 0, 5)
row 2 = (6, 7, 8)
```
```python
if state[i][j] == 0:
```
This checks whether current cell contains blank tile 0.

Example:
```python
state[1][1] == 0
```
Because:
```python
(4, 0, 5)
```
Here 0 is in row 1, column 1.

Simply, **find_blank()** searches the 3x3 puzzle and returns the row and column position of the blank tile represented by 0.

4. Successor Generation Function:
```python
def get_successors(state):
    successors = []
    x, y = find_blank(state)
    moves = [(-1,0), (1,0), (0,-1), (0,1)]
```
This function creates all possible next puzzle states.

A successor means next possible state after one valid move.
```python
x, y = find_blank(state)
```
This calls **find_blank() function**.

It gets blank tile position.

Example:
```python
x = 1
y = 1
```
Here:
```bash
Variable      Meaning
x	            Row position of blank
y	            Column position of blank
```
```python
moves = [(-1,0), (1,0), (0,-1), (0,1)]
```
This stores all possible moves of blank tile.
```bash
Move	        Meaning
(-1, 0)	      Up
(1, 0)	      Down
(0, -1)	      Left
(0, 1)	      Right
```
> Why?

If blank is at (x, y):

> (-1, 0) Up:
```bash
x - 1, y
```
> (1, 0) Down:
```bash
x + 1, y
```
> (0, -1) Left:
```bash
x, y - 1
```
> (0, 1) Right:
```bash
x, y + 1
```

5. Trying Each Move:
```python
for dx, dy in moves:
    nx, ny = x + dx, y + dy
```
nx = New row position
ny = New column position

Suppose blank position is:
```python
x = 1
y = 1
```
For Up move:
```python
dx = -1
dy = 0
```
So:
```python
nx = x + dx
nx = 1 + (-1) = 0

ny = y + dy
ny = 1 + 0 = 1
```
New blank position becomes:
```python
(0, 1)
```

6. Checking Valid Move:
```python
if 0 <= nx < 3 and 0 <= ny < 3:
```
This checks whether new position is inside the 3x3 board.

- This condition prevents invalid moves outside the puzzle boundary.

7. Creating a New State:
```python
new_state = [list(row) for row in state]
```

This line converts tuple rows into list rows.

> Why?

Your puzzle state is stored as tuple:
```python
(
    (1, 2, 3),
    (4, 0, 5),
    (6, 7, 8)
)
```
Tuple cannot be changed directly.
But we need to swap blank with another tile. So we convert it to list.

After conversion:
```python
[
    [1, 2, 3],
    [4, 0, 5],
    [6, 7, 8]
]
```

8. Swapping Blank Tile:
```python
new_state[x][y], new_state[nx][ny] = new_state[nx][ny], new_state[x][y]
```
This is the main puzzle movement line.

It swaps blank tile with neighboring tile.

Suppose current board:
```python
[
    [1, 2, 3],
    [4, 0, 5],
    [6, 7, 8]
]
```
Blank position:
```python
x = 1
y = 1
```
If move Right:
```python
nx = 1
ny = 2
```
Then it swaps:
```python
new_state[1][1] = 0
new_state[1][2] = 5
```
After swap:
```python
[
    [1, 2, 3],
    [4, 5, 0],
    [6, 7, 8]
]
```
Easy meaning:

Blank 0 moves right and tile 5 moves left.

- This line performs the actual move by swapping the blank tile with the selected neighboring tile.


9. Adding New State to Successor List:
```python
successors.append(tuple(tuple(row) for row in new_state))
```
This converts the list back into tuple and stores it.

> Why convert back to tuple?

Because later we store states inside a set called visited.

- Python set cannot store list because list is mutable/changeable.

- Tuple is immutable, so it can be stored in set.

10. BFS Function:
```python
def bfs(start, goal):
```

This function solves puzzle using **BFS**.

**BFS** means **Breadth First Search**.

It explores states level by level.

Example:
```bash
Start state
→ all states after 1 move
→ all states after 2 moves
→ all states after 3 moves
```
So BFS finds the shortest solution path.

Queue Initialization
```python
queue = deque([(start, [start])])
```

This creates a queue.

Each item inside queue contains two things:
```python
(state, path)
```
```bash
Part	    Meaning
state	    Current board
path	    Full route from start to this state
```

At first:
```python
state = start
path = [start]
```
So queue starts with the initial puzzle.
```python
visited = set()
```
This creates an empty set.

It stores already visited states.

- Why needed?

To avoid repeating same state again and again.

Without visited set, program may enter infinite loop.
```python
visited.add(start)
```
This marks the start state as visited.

So BFS will not process the same start state again.

11. BFS Loop
```python
while queue:
```
This loop runs as long as queue is not empty.

Meaning:

“As long as there are states to explore, continue searching.”

If queue becomes empty and goal not found, then no solution.
```python
state, path = queue.popleft()
```
This removes the first item from queue.

Because BFS uses FIFO:
```bash
First In, First Out
```
```bash
Part	          Meaning
popleft()	      Remove item from left/front side
state	          Current puzzle state
path	          Path used to reach this state
```

Example:

If queue has:
```python
deque([
    (A, pathA),
    (B, pathB),
    (C, pathC)
])
```
popleft() takes A first.

12. Checking Goal Inside BFS
```python
if is_goal(state, goal):
    return path
```
This checks whether current state is goal.

If yes, BFS stops and returns solution path.

- Why return path?

Because path contains every step from initial state to goal state.

Example:
```python
[
    initial_state,
    step1,
    step2,
    goal_state
]
```

13. Generating Next States in BFS
```python
for succ in get_successors(state):
```
This generates all possible next states from current state.
```bash
Part	                    Meaning
succ	                    One successor / next state
get_successors(state)	    Function that gives valid next boards
```
```python
if succ not in visited:
```
This checks whether this next state was already visited.

If not visited, we can explore it.
```python
visited.add(succ)
```
This marks successor as visited.

So later we do not repeat it.
```python
queue.append((succ, path + [succ]))
```
This adds new state into queue.

It also updates the path.

Suppose current path is:

```python
[start]
```
New successor is:
```python
succ
```
Then:
```python
path + [succ]
```
becomes:
```python
[start, succ]
```
So BFS remembers how it reached that state.

Important:

path + [succ] creates a new path list.
It does not destroy old path.
```python
return None
```
If queue becomes empty and goal is not found, the function returns None.

Meaning:

No solution found.

14. Printing the Solution
```python
if solution:
```
This checks whether solution exists.

If solution is not None, then this block runs.
```python
print(f"Solution found in {len(solution)-1} moves:")
```

Word by word:
```
Part	                Meaning
print()	              Output show kore
f"..."	              f-string, variable value string er moddhe show kora jay
len(solution)	        Total states in solution path
len(solution)-1	      Number of moves
```
- Why minus 1?

Because path includes initial state.

Example:
```python
[start, step1, step2, goal]
```
Total states = 4
Moves = 3

So:
```python
len(solution) - 1
```
```python
for step in solution:
```
This loop prints each puzzle state from start to goal.

step means one board configuration.
```python
for row in step:
```
Each step has 3 rows.

This loop prints each row.
```python
print(row)
```
This prints one row of puzzle.

Example:
```bash
(1, 2, 3)
```

**Full Program Flow**

The code works like this:

```bash
1. Start from initial puzzle.
2. Find blank tile position.
3. Generate all valid next states.
4. Use BFS queue to explore states level by level.
5. Avoid repeated states using visited set.
6. Check each state with goal state.
7. When goal is found, return full path.
8. Print every step of the solution.
```

8-Puzzle using BFS
"""

# Import deque from collections for efficient queue operations
from collections import deque  # deque = Double-ended queue, fast queue operation er jonno use hoy

# --- Check if state is goal ---
# Function to check if the current state is the same as the goal state
def is_goal(state, goal):
    return state == goal

# --- Find blank position ---
# Function to find the position of the blank tile (represented by 0)
def find_blank(state):
    for i in range(3):  # Loop through rows
        for j in range(3):  # Loop through columns
            if state[i][j] == 0:  # If the cell contains blank (0)
                return i, j  # Return its position (row, column)

# --- Generate successors ---
# Function to generate all possible next states by moving the blank tile
def get_successors(state):
    successors = []  # List to store next states
    x, y = find_blank(state)  # Get blank tile position
    moves = [(-1,0), (1,0), (0,-1), (0,1)]  # Possible moves: Up, Down, Left, Right

    for dx, dy in moves:  # Try each move
        nx, ny = x + dx, y + dy  # New position of blank
        if 0 <= nx < 3 and 0 <= ny < 3:  # Ensure move is within bounds
            # Convert state to a mutable list of lists
            new_state = [list(row) for row in state]
            #print(new_state)
            # Swap blank with the neighboring tile
            new_state[x][y], new_state[nx][ny] = new_state[nx][ny], new_state[x][y]
            # Convert back to tuple of tuples (so it can be stored in a set)
            #print(successors)
            successors.append(tuple(tuple(row) for row in new_state))
    return successors  # Return all possible next states

# --- BFS Search ---
# Function to perform Breadth-First Search to find the solution path
def bfs(start, goal):
    # Initialize queue with the start state and its path
    queue = deque([(start, [start])])
    visited = set()  # Set to keep track of visited states
    visited.add(start)  # Mark start state as visited

    while queue:  # While there are states to explore
        state, path = queue.popleft()  # Get the first state and its path
        if is_goal(state, goal):  # If goal is reached
            return path  # Return the solution path
        for succ in get_successors(state):  # Generate next states
            if succ not in visited:  # If not already visited
                visited.add(succ)  # Mark as visited
                queue.append((succ, path + [succ]))  # Add new state with updated path
    return None  # Return None if no solution is found


# --- Initial and Goal States ---
# Define the starting configuration of the puzzle
initial_state = (
    (1, 2, 3),
    (4, 0, 5),
    (6, 7, 8)
)

# Define the goal configuration of the puzzle
goal_state = (
    (1, 2, 3),
    (4, 5, 6),
    (7, 8, 0)
)

# --- Solve ---
# Run BFS to find a solution from initial to goal state
solution = bfs(initial_state, goal_state)

# --- Print Solution ---
# If a solution is found, display it step by step
if solution:
    print(f"Solution found in {len(solution)-1} moves:")
    for step in solution:  # Print each step in the solution path
        for row in step:  # Print each row of the puzzle
            print(row)
        print()  # Blank line between steps
else:
    print("No solution found.")  # If no solution exists

"""- **What is state?**

A **state** means one arrangement of the puzzle.

Example:
```python
(
    (1, 2, 3),
    (4, 0, 5),
    (6, 7, 8)
)
```
This is one state.

- **What is state space?**

All possible puzzle configurations together are called state space.

In 8-puzzle, there are many possible states.

- **What is successor?**

A successor is a new state generated from current state by one valid move.

Example:

Blank moves right:
```python
(1, 2, 3)
(4, 0, 5)
(6, 7, 8)
```
becomes:
```python
(1, 2, 3)
(4, 5, 0)
(6, 7, 8)
```
- **Why use BFS?**

BFS explores level by level.

So it finds the **shortest path** in terms of number of moves.

- **Why use queue?**

BFS needs queue because it follows:
```bash
First In, First Out
```
The state added first is explored first.

- **Why use visited set?**

To avoid visiting same puzzle state repeatedly.

Without visited:
```bash
The blank may move left, then right, then left again forever.
```
So **visited** prevents infinite repetition.

- **Why use tuple instead of list?**

Because tuple can be stored in a set.

List cannot be stored in set because list is changeable.

So:
```python
visited.add(state)
```
works only when state is tuple.

- **Very Simple Viva Explanation**

This program solves the **8-puzzle using BFS**. First, it represents the puzzle as a tuple of tuples, where **0** means the **blank tile.** The **find_blank()** function finds the position of 0. The **get_successors()** function generates all valid next states by moving the blank tile up, down, left, or right. Then the **bfs()** function uses a queue to explore states level by level and a visited set to avoid repeated states. When the current state matches the goal state, it returns the complete solution path and prints each step.

8-Puzzle using DFS
"""

# =====================================================
# 8-Puzzle Problem using DFS
# =====================================================

# --- Check if state is goal ---
def is_goal(state, goal):
    return state == goal


# --- Find blank position ---
def find_blank(state):
    for i in range(3):
        for j in range(3):
            if state[i][j] == 0:
                return i, j


# --- Generate successors ---
def get_successors(state):
    successors = []
    x, y = find_blank(state)

    # Possible moves: Up, Down, Left, Right
    moves = [(-1, 0), (1, 0), (0, -1), (0, 1)]

    for dx, dy in moves:
        nx, ny = x + dx, y + dy

        if 0 <= nx < 3 and 0 <= ny < 3:
            new_state = [list(row) for row in state]

            # Swap blank tile with neighbor tile
            new_state[x][y], new_state[nx][ny] = new_state[nx][ny], new_state[x][y]

            # Convert list back to tuple
            successors.append(tuple(tuple(row) for row in new_state))

    return successors


# --- DFS Search ---
def dfs(start, goal):
    stack = [(start, [start])]
    visited = set()

    while stack:
        state, path = stack.pop()

        if is_goal(state, goal):
            return path

        if state not in visited:
            visited.add(state)

            for successor in get_successors(state):
                if successor not in visited:
                    stack.append((successor, path + [successor]))

    return None


# --- Print Solution ---
def print_solution(solution):
    if solution:
        print(f"Solution found in {len(solution)-1} moves:")

        for step in solution:
            for row in step:
                print(row)
            print()
    else:
        print("No solution found.")


# --- Initial State ---
initial_state = (
    (1, 2, 3),
    (4, 0, 5),
    (6, 7, 8)
)

# --- Goal State ---
goal_state = (
    (1, 2, 3),
    (4, 5, 6),
    (7, 8, 0)
)


# --- Run DFS ---
solution = dfs(initial_state, goal_state)
print_solution(solution)

# --- Final Line ---
if solution:
    print(f"Solution found in {len(solution)-1} moves.")
else:
    print("No solution found.")

"""8-Puzzle using DLS"""

# =====================================================
# 8-Puzzle Problem using DLS
# =====================================================

# --- Check if state is goal ---
def is_goal(state, goal):
    return state == goal


# --- Find blank position ---
def find_blank(state):
    for i in range(3):
        for j in range(3):
            if state[i][j] == 0:
                return i, j


# --- Generate successors ---
def get_successors(state):
    successors = []
    x, y = find_blank(state)

    # Possible moves: Up, Down, Left, Right
    moves = [(-1, 0), (1, 0), (0, -1), (0, 1)]

    for dx, dy in moves:
        nx, ny = x + dx, y + dy

        if 0 <= nx < 3 and 0 <= ny < 3:
            new_state = [list(row) for row in state]

            # Swap blank tile with neighbor tile
            new_state[x][y], new_state[nx][ny] = new_state[nx][ny], new_state[x][y]

            # Convert list back to tuple
            successors.append(tuple(tuple(row) for row in new_state))

    return successors


# --- DLS Search ---
def dls(start, goal, limit):
    return recursive_dls(start, goal, limit, [start])


def recursive_dls(state, goal, limit, path):
    if is_goal(state, goal):
        return path

    if limit == 0:
        return None

    for successor in get_successors(state):
        # Avoid repeated state in the current path
        if successor not in path:
            result = recursive_dls(successor, goal, limit - 1, path + [successor])

            if result is not None:
                return result

    return None


# --- Print Solution ---
def print_solution(solution):
    if solution:
        print(f"Solution found in {len(solution)-1} moves:")

        for step in solution:
            for row in step:
                print(row)
            print()
    else:
        print("No solution found.")


# --- Initial State ---
initial_state = (
    (1, 2, 3),
    (4, 0, 5),
    (6, 7, 8)
)

# --- Goal State ---
goal_state = (
    (1, 2, 3),
    (4, 5, 6),
    (7, 8, 0)
)


# --- Run DLS ---
depth_limit = 20
solution = dls(initial_state, goal_state, depth_limit)
print_solution(solution)

"""8-Puzzle using IDS"""

# =====================================================
# 8-Puzzle Problem using IDS
# =====================================================

# --- Check if state is goal ---
def is_goal(state, goal):
    return state == goal


# --- Find blank position ---
def find_blank(state):
    for i in range(3):
        for j in range(3):
            if state[i][j] == 0:
                return i, j


# --- Generate successors ---
def get_successors(state):
    successors = []
    x, y = find_blank(state)

    # Possible moves: Up, Down, Left, Right
    moves = [(-1, 0), (1, 0), (0, -1), (0, 1)]

    for dx, dy in moves:
        nx, ny = x + dx, y + dy

        if 0 <= nx < 3 and 0 <= ny < 3:
            new_state = [list(row) for row in state]

            # Swap blank tile with neighbor tile
            new_state[x][y], new_state[nx][ny] = new_state[nx][ny], new_state[x][y]

            # Convert list back to tuple
            successors.append(tuple(tuple(row) for row in new_state))

    return successors


# --- DLS Function for IDS ---
def dls(start, goal, limit):
    return recursive_dls(start, goal, limit, [start])


def recursive_dls(state, goal, limit, path):
    if is_goal(state, goal):
        return path

    if limit == 0:
        return None

    for successor in get_successors(state):
        # Avoid repeated state in the current path
        if successor not in path:
            result = recursive_dls(successor, goal, limit - 1, path + [successor])

            if result is not None:
                return result

    return None


# --- IDS Search ---
def ids(start, goal, max_depth):
    for depth in range(max_depth + 1):
        print(f"Checking depth limit: {depth}")

        result = dls(start, goal, depth)

        if result is not None:
            return result

    return None


# --- Print Solution ---
def print_solution(solution):
    if solution:
        print(f"Solution found in {len(solution)-1} moves:")

        for step in solution:
            for row in step:
                print(row)
            print()
    else:
        print("No solution found.")


# --- Initial State ---
initial_state = (
    (1, 2, 3),
    (4, 0, 5),
    (6, 7, 8)
)

# --- Goal State ---
goal_state = (
    (1, 2, 3),
    (4, 5, 6),
    (7, 8, 0)
)


# --- Run IDS ---
max_depth = 30
solution = ids(initial_state, goal_state, max_depth)
print_solution(solution)