"""Lab_report1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DRpHul3ug9TG0uliRyBv2CE0fDGATy2i

**BFS (Breadth-First Search)**
- It's a graph traversal algorithm used to explore nodes in a graph.
- It explores all the nodes at the current level and after that move on to the next level.

**Eating logic**

- m_left > 0: If there are no missionaries on the left, they are safe (there is no one to eat).
- m_left < c_left: If there are missionaries, but fewer than cannibals, the state is invalid because the missionaries would be eaten.
"""

# Changes some work, which helps to prevent duplicate queue growth via visited-state marking, strict validation, and explicit error handling.

from collections import deque

# Given input
# TOTAL_MISSIONARIES = 3
# TOTAL_CANNIBALS = 3

# Input Flexibility
M = int(input("Enter the number of missionaries: "))
C = int(input("Enter the number of cannibals: "))

TOTAL_MISSIONARIES = M
TOTAL_CANNIBALS = C
VALID_BOAT_SIDES = {"L", "R"}  # Boat capacity [2]
MOVES = ((1, 0), (2, 0), (0, 1), (0, 2), (1, 1))

# State Representation
# Dynamic Validation
def is_valid(m_left, c_left, boat, m_right, c_right):
    if boat not in VALID_BOAT_SIDES:
        return False

    values = (m_left, c_left, m_right, c_right)
    if any(not isinstance(v, int) for v in values):
        return False

    if any(v < 0 for v in values):
        return False

    if m_left + m_right != TOTAL_MISSIONARIES:
        return False

    if c_left + c_right != TOTAL_CANNIBALS:
        return False

    if m_left > 0 and m_left < c_left:
        return False

    if m_right > 0 and m_right < c_right:
        return False

    return True


def get_successors(state):
    if not isinstance(state, tuple) or len(state) != 5:
        raise ValueError("State must be a 5-item tuple: (m_left, c_left, boat, m_right, c_right)")

    m_left, c_left, boat, m_right, c_right = state

    if not is_valid(m_left, c_left, boat, m_right, c_right):
        raise ValueError(f"Invalid state: {state}")

    successors = []

    for m, c in MOVES:
        if boat == "L":
            new_state = (m_left - m, c_left - c, "R", m_right + m, c_right + c)
        else:
            new_state = (m_left + m, c_left + c, "L", m_right - m, c_right - c)

        if is_valid(*new_state):
            successors.append(new_state)

    return successors

# BFS
def bfs(start, goal):
    if not is_valid(*start):
        raise ValueError(f"Invalid start state: {start}")

    if not is_valid(*goal):
        raise ValueError(f"Invalid goal state: {goal}")

    queue = deque([(start, [start])])
    visited = {start}

    while queue:
        state, path = queue.popleft()

        if state == goal:
            return path

        for succ in get_successors(state):
            if succ not in visited:
                visited.add(succ)
                queue.append((succ, path + [succ]))

    return None

# Based on the given input
# start_state = (3, 3, "L", 0, 0)
# goal_state = (0, 0, "R", 3, 3)

# Example usage with dynamic input
start_state = (TOTAL_MISSIONARIES, TOTAL_CANNIBALS, "L", 0, 0)
goal_state = (0, 0, "R", TOTAL_MISSIONARIES, TOTAL_CANNIBALS)

# Execution
try:
    solution = bfs(start_state, goal_state)

    if solution:
        print(f"Solution found in {len(solution) - 1} steps:")
        for step_no, step in enumerate(solution):
            print(f"Step {step_no}: {step}")
    else:
        print("No solution found.")
except ValueError as exc:
    print(f"Error: {exc}")