# -*- coding: utf-8 -*-
"""Lab_report6_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n7g7u9sEgDLNIN1WEvbNF9_VRwWIqT2Q

**Adversarial Search** using **Alpha-Beta Pruning Algorithm** (Tic-Tac-Toe)
"""

import math

def print_board(board):
    """Display the board in 3×3 format."""
    for i in range(0, 9, 3):
        print(board[i:i + 3])

def check_winner(board):
    """Return the winner, draw, or None."""
    winning_positions = [
        (0, 1, 2), (3, 4, 5), (6, 7, 8),
        (0, 3, 6), (1, 4, 7), (2, 5, 8),
        (0, 4, 8), (2, 4, 6)
    ]

    for a, b, c in winning_positions:
        if board[a] == board[b] == board[c] and board[a] != " ":
            return board[a]

    if " " not in board:
        return "Draw"

    return None

def alpha_beta(board, alpha, beta, is_maximizing):
    """Evaluate the board using Alpha-Beta Pruning."""

    result = check_winner(board)

    if result == "O":
        return 1
    if result == "X":
        return -1
    if result == "Draw":
        return 0

    if is_maximizing:
        best_score = -math.inf

        for i in range(9):
            if board[i] == " ":
                board[i] = "O"
                score = alpha_beta(board, alpha, beta, False)
                board[i] = " "

                best_score = max(best_score, score)
                alpha = max(alpha, best_score)

                if beta <= alpha:
                    break

        return best_score

    else:
        best_score = math.inf

        for i in range(9):
            if board[i] == " ":
                board[i] = "X"
                score = alpha_beta(board, alpha, beta, True)
                board[i] = " "

                best_score = min(best_score, score)
                beta = min(beta, best_score)

                if beta <= alpha:
                    break

        return best_score

def best_move(board):
    """Find the best move for the AI."""

    best_score = -math.inf
    move = -1

    for i in range(9):
        if board[i] == " ":
            board[i] = "O"
            score = alpha_beta(board, -math.inf, math.inf, False)
            board[i] = " "

            if score > best_score:
                best_score = score
                move = i

    return move

# Example

board = [" "] * 9

board[3] = "X"

print("Current Board:")
print_board(board)

move = best_move(board)

print("\nAI chooses position:", move)

"""# Explanation

## Objective

The Alpha-Beta Pruning algorithm improves the Minimax algorithm by eliminating unnecessary branches during the search. It still finds the best move but evaluates fewer game states, making it faster.

---

# Function Explanation

## 1. `print_board(board)`

Displays the Tic-Tac-Toe board in a 3×3 format.

---

## 2. `check_winner(board)`

Checks whether:

* AI (`O`) wins
* Human (`X`) wins
* Match is a draw
* Game is still in progress

Return values:

```text
"O"      -> AI wins
"X"      -> Human wins
"Draw"   -> Match is tied
None     -> Game continues
```

---

## 3. `alpha_beta(board, alpha, beta, is_maximizing)`

This is the main function of the algorithm.

Like Minimax, it explores possible moves recursively. However, it uses two additional values:

* **Alpha (α):** The best score the maximizing player (AI) can guarantee.
* **Beta (β):** The best score the minimizing player (Human) can guarantee.

If a branch cannot produce a better result than the current alpha or beta value, it is ignored.

This process is called **pruning**.

---

## 4. `best_move(board)`

Checks every possible move for the AI.

For each empty position:

* Place `O`
* Evaluate the move using Alpha-Beta Pruning
* Undo the move
* Keep the move with the highest score

Finally, the function returns the best move.

---

# Working Process

```text
Current Board
      │
      ▼
Check every empty position
      │
      ▼
Place O temporarily
      │
      ▼
Run Alpha-Beta recursively
      │
      ▼
Update Alpha and Beta values
      │
      ▼
Prune unnecessary branches
      │
      ▼
Return best score
      │
      ▼
Choose optimal move
```

---

# Alpha and Beta Values

### Alpha (α)

* Represents the best score found so far for the maximizing player (AI).
* Initially set to negative infinity.

Example:

```text
alpha = -∞
```

---

### Beta (β)

* Represents the best score found so far for the minimizing player (Human).
* Initially set to positive infinity.

Example:

```text
beta = +∞
```

---

### Pruning Condition

```python
if beta <= alpha:
    break
```

When this condition becomes true, the remaining branches are skipped because they cannot improve the final decision.

---

# Sample Output

```text
Current Board:
[' ', ' ', ' ']
['X', ' ', ' ']
[' ', ' ', ' ']

AI chooses position: 4
```

The AI selects the center position because it is the strongest strategic move.

---

# Time Complexity

### Worst Case

```text
O(b^d)
```

The worst-case performance is the same as Minimax when pruning is ineffective.

### Best Case

```text
O(b^(d/2))
```

With effective move ordering, Alpha-Beta Pruning examines significantly fewer nodes, making it much faster.

where:

* **b** = branching factor
* **d** = depth of the game tree

---

# Space Complexity

```text
O(d)
```

The recursive call stack grows with the depth of the search tree.

---

# Advantages

* Produces the same optimal result as Minimax.
* Evaluates fewer game states.
* Faster than standard Minimax.
* Suitable for deeper search trees.
* Improves the efficiency of adversarial search.

---

# Limitations

* Performance depends on the order in which moves are explored.
* More complex than standard Minimax.
* Worst-case time complexity remains the same as Minimax.

---

# Viva Questions

### Q1. What is Alpha-Beta Pruning?

**Answer:**
Alpha-Beta Pruning is an optimization of the Minimax algorithm that skips branches which cannot affect the final decision, reducing the number of nodes evaluated.

---

### Q2. What does Alpha represent?

**Answer:**
Alpha is the best score that the maximizing player (AI) can guarantee at any point during the search.

---

### Q3. What does Beta represent?

**Answer:**
Beta is the best score that the minimizing player (Human) can guarantee during the search.

---

### Q4. What is pruning?

**Answer:**
Pruning is the process of ignoring branches that cannot improve the final result, reducing unnecessary calculations.

---

### Q5. Does Alpha-Beta Pruning change the final answer?

**Answer:**
No. It always returns the same optimal move as the Minimax algorithm but reaches the result more efficiently.

---

# Comparison: Minimax vs. Alpha-Beta Pruning

| Feature                    | Minimax                     | Alpha-Beta Pruning                      |
| -------------------------- | --------------------------- | --------------------------------------- |
| Purpose                    | Finds the optimal move      | Finds the optimal move more efficiently |
| Search Strategy            | Explores all possible moves | Skips unnecessary branches              |
| Pruning                    | No                          | Yes                                     |
| Speed                      | Slower                      | Faster                                  |
| Number of Nodes Explored   | More                        | Fewer                                   |
| Worst-Case Time Complexity | O(b^d)                      | O(b^d)                                  |
| Best-Case Time Complexity  | O(b^d)                      | O(b^(d/2))                              |
| Space Complexity           | O(d)                        | O(d)                                    |
| Final Decision             | Optimal                     | Optimal                                 |

---

# Conclusion

Minimax and Alpha-Beta Pruning are both adversarial search algorithms used to determine the optimal move in two-player games. Minimax evaluates every possible game state to guarantee the best decision, but this can be computationally expensive. Alpha-Beta Pruning improves Minimax by eliminating branches that cannot influence the final outcome. As a result, it produces the same optimal move while exploring fewer game states, making it faster and more efficient for game-playing applications.

"""