# -*- coding: utf-8 -*-
"""Lab6_Whole.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d2kDXMUTK6_hJK5p1zeFbZTpmQI5SapG
"""

import math

def print_board(board):
    for row in [board[i:i+3] for i in range(0, 9, 3)]:
        print(row)

def check_winner(board):
    win_combinations = [
        (0,1,2), (3,4,5), (6,7,8),
        (0,3,6), (1,4,7), (2,5,8),
        (0,4,8), (2,4,6)
    ]

    for a, b, c in win_combinations:
        if board[a] == board[b] == board[c] and board[a] != " ":
            return board[a]

    if " " not in board:
        return "Draw"

    return None

def minimax(board, is_maximizing):
    winner = check_winner(board)

    if winner == "X":
        return -1
    if winner == "O":
        return 1
    if winner == "Draw":
        return 0

    if is_maximizing:
        best_score = -math.inf

        for i in range(9):
            if board[i] == " ":
                board[i] = "O"
                score = minimax(board, False)
                board[i] = " "
                best_score = max(best_score, score)

        return best_score

    else:
        best_score = math.inf

        for i in range(9):
            if board[i] == " ":
                board[i] = "X"
                score = minimax(board, True)
                board[i] = " "
                best_score = min(best_score, score)

        return best_score

def best_move(board):
    best_score = -math.inf
    move = None

    for i in range(9):
        if board[i] == " ":
            board[i] = "O"
            score = minimax(board, False)
            board[i] = " "

            if score > best_score:
                best_score = score
                move = i

    return move

board = [" "] * 9
board[0] = "X"

print_board(board)
print("AI chooses position:", best_move(board))

import math

def print_board(board):
    for row in [board[i:i+3] for i in range(0, 9, 3)]:
        print(row)

def check_winner(board):
    win_combinations = [
        (0,1,2), (3,4,5), (6,7,8),
        (0,3,6), (1,4,7), (2,5,8),
        (0,4,8), (2,4,6)
    ]

    for a, b, c in win_combinations:
        if board[a] == board[b] == board[c] and board[a] != " ":
            return board[a]

    if " " not in board:
        return "Draw"

    return None

def alpha_beta(board, depth, alpha, beta, is_maximizing):
    winner = check_winner(board)

    if winner == "X":
        return -1
    if winner == "O":
        return 1
    if winner == "Draw":
        return 0

    if is_maximizing:
        max_eval = -math.inf

        for i in range(9):
            if board[i] == " ":
                board[i] = "O"
                eval = alpha_beta(board, depth + 1, alpha, beta, False)
                board[i] = " "
                max_eval = max(max_eval, eval)
                alpha = max(alpha, eval)

                if beta <= alpha:
                    break

        return max_eval

    else:
        min_eval = math.inf

        for i in range(9):
            if board[i] == " ":
                board[i] = "X"
                eval = alpha_beta(board, depth + 1, alpha, beta, True)
                board[i] = " "
                min_eval = min(min_eval, eval)
                beta = min(beta, eval)

                if beta <= alpha:
                    break

        return min_eval

def best_move(board):
    best_score = -math.inf
    move = None

    for i in range(9):
        if board[i] == " ":
            board[i] = "O"
            score = alpha_beta(board, 0, -math.inf, math.inf, False)
            board[i] = " "

            if score > best_score:
                best_score = score
                move = i

    return move

board = [" "] * 9
board[3] = "X"

print_board(board)
print("AI chooses position:", best_move(board))