# -*- coding: utf-8 -*-
"""Lab_report6_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ufm8N94pZePdatxeNp1FR9KnkxzrK8cd

**Adversarial Search** using **Minimax Algorithm** (Tic-Tac-Toe)
"""

import math

def print_board(board):
    """Display the board in 3×3 format."""
    for i in range(0, 9, 3):
        print(board[i:i + 3])

def check_winner(board):
    """Return the winner, draw, or None."""
    winning_positions = [
        (0, 1, 2), (3, 4, 5), (6, 7, 8),
        (0, 3, 6), (1, 4, 7), (2, 5, 8),
        (0, 4, 8), (2, 4, 6)
    ]

    for a, b, c in winning_positions:
        if board[a] == board[b] == board[c] and board[a] != " ":
            return board[a]

    if " " not in board:
        return "Draw"

    return None

def minimax(board, is_maximizing):
    """Evaluate the board using the Minimax algorithm."""

    result = check_winner(board)

    if result == "O":
        return 1
    if result == "X":
        return -1
    if result == "Draw":
        return 0

    if is_maximizing:
        best_score = -math.inf

        for i in range(9):
            if board[i] == " ":
                board[i] = "O"
                score = minimax(board, False)
                board[i] = " "
                best_score = max(best_score, score)

        return best_score

    else:
        best_score = math.inf

        for i in range(9):
            if board[i] == " ":
                board[i] = "X"
                score = minimax(board, True)
                board[i] = " "
                best_score = min(best_score, score)

        return best_score

def best_move(board):
    """Find the best move for the AI."""

    best_score = -math.inf
    move = -1

    for i in range(9):
        if board[i] == " ":
            board[i] = "O"
            score = minimax(board, False)
            board[i] = " "

            if score > best_score:
                best_score = score
                move = i

    return move

# Example

board = [" "] * 9

board[0] = "X"

print("Current Board:")
print_board(board)

move = best_move(board)

print("\nAI chooses position:", move)

"""# Explanation

## Objective

The Minimax algorithm is an **adversarial search algorithm** used in two-player games such as Tic-Tac-Toe, Chess, and Checkers. It assumes that both players always play their best possible moves.

In this program:

* **Human (X)** is the **Minimizing Player**
* **AI (O)** is the **Maximizing Player**

---

# Function Explanation

## 1. `print_board(board)`

Displays the Tic-Tac-Toe board in a 3×3 format.

Example:

```
['X', ' ', ' ']
[' ', ' ', ' ']
[' ', ' ', ' ']
```

---

## 2. `check_winner(board)`

Checks whether:

* X wins
* O wins
* Match is a draw
* Game is still running

Return values:

```
"X"      -> Human wins
"O"      -> AI wins
"Draw"   -> No empty spaces left
None     -> Game continues
```

---

## 3. `minimax(board, is_maximizing)`

This is the core function.

It recursively explores **every possible future move** until the game ends.

If it is AI's turn:

* Try every possible move.
* Choose the move with the **highest score**.

If it is Human's turn:

* Try every possible move.
* Choose the move with the **lowest score**.

Evaluation values:

```
AI wins      = 1
Draw         = 0
Human wins   = -1
```

---

## 4. `best_move(board)`

Checks every empty position.

For each possible move:

* Place AI's symbol (`O`)
* Run Minimax
* Undo the move
* Keep the move with the highest score

Finally, it returns the best position for the AI.

---

# Working Process

```
Current Board
      │
      ▼
Check every empty position
      │
      ▼
Place O temporarily
      │
      ▼
Run Minimax recursively
      │
      ▼
Evaluate all future moves
      │
      ▼
Return score
      │
      ▼
Choose highest score
      │
      ▼
Best move found
```

---

# Sample Output

```
Current Board:
['X', ' ', ' ']
[' ', ' ', ' ']
[' ', ' ', ' ']

AI chooses position: 4
```

The AI selects the center position because it provides the best chance of winning or forcing a draw.

---

# Time Complexity

Worst Case:

```
O(b^d)
```

where:

* **b** = branching factor (maximum possible moves)
* **d** = depth of the game tree

Since Minimax evaluates all possible game states, its execution time increases rapidly as the search depth grows.

---

# Space Complexity

```
O(d)
```

The recursive calls use stack memory proportional to the depth of the game tree.

---

# Advantages

* Always finds the optimal move.
* Guarantees the best outcome if both players play perfectly.
* Easy to understand and implement.
* Suitable for small games like Tic-Tac-Toe.

---

# Limitations

* Explores every possible move.
* Becomes slow for larger games.
* Performs many unnecessary calculations.

---

# Questions

### Q1. What is the Minimax algorithm?

**Answer:**
Minimax is an adversarial search algorithm that finds the best move by assuming both players always make optimal decisions.

---

### Q2. Why is AI called the Maximizing player?

**Answer:**
The AI tries to maximize its score and select the move that gives the highest possible outcome.

---

### Q3. Why is the human called the Minimizing player?

**Answer:**
The human attempts to minimize the AI's score by choosing moves that are least favorable to the AI.

---

### Q4. Why do we undo each move after recursion?

**Answer:**
Undoing the move (backtracking) restores the board to its previous state so that other possible moves can be evaluated correctly.

---

### Q5. What is the biggest drawback of Minimax?

**Answer:**
It evaluates every possible game state, making it computationally expensive for games with large search spaces.

---

"""