# -*- coding: utf-8 -*-
"""Lab3(5/17/2026).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V0ZaN7BOi_rd8xyQkiGRs611K8_YzjX5
"""

#Informed Search Algorithms:  A* Search (Romania Road Map Problem Search)
# --- Graph definition: each city has neighbors with distances (road distances in km) ---
graph = {
    'Arad': {'Zerind': 75, 'Sibiu': 140, 'Timisoara': 118},
    'Zerind': {'Arad': 75, 'Oradea': 71},
    'Oradea': {'Zerind': 71, 'Sibiu': 151},
    'Sibiu': {'Arad': 140, 'Oradea': 151, 'Fagaras': 99, 'Rimnicu Vilcea': 80},
    'Fagaras': {'Sibiu': 99, 'Bucharest': 211},
    'Rimnicu Vilcea': {'Sibiu': 80, 'Pitesti': 97, 'Craiova': 146},
    'Pitesti': {'Rimnicu Vilcea': 97, 'Bucharest': 101, 'Craiova': 138},
    'Craiova': {'Rimnicu Vilcea': 146, 'Pitesti': 138, 'Drobeta': 120},
    'Drobeta': {'Craiova': 120, 'Mehadia': 75},
    'Mehadia': {'Drobeta': 75, 'Lugoj': 70},
    'Lugoj': {'Mehadia': 70, 'Timisoara': 111},
    'Timisoara': {'Arad': 118, 'Lugoj': 111},
    'Bucharest': {'Fagaras': 211, 'Pitesti': 101, 'Giurgiu': 90, 'Urziceni': 85},
    'Giurgiu': {'Bucharest': 90},
    'Urziceni': {'Bucharest': 85, 'Hirsova': 98, 'Vaslui': 142},
    'Hirsova': {'Urziceni': 98, 'Eforie': 86},
    'Eforie': {'Hirsova': 86},
    'Vaslui': {'Urziceni': 142, 'Iasi': 92},
    'Iasi': {'Vaslui': 92, 'Neamt': 87},
    'Neamt': {'Iasi': 87}
}

# --- Straight-Line Distance heuristic: estimated distance from each city to Bucharest ---
heuristic = {
    'Arad': 366,
    'Bucharest': 0,
    'Craiova': 160,
    'Drobeta': 242,
    'Eforie': 161,
    'Fagaras': 176,
    'Giurgiu': 77,
    'Hirsova': 151,
    'Iasi': 226,
    'Lugoj': 244,
    'Mehadia': 241,
    'Neamt': 234,
    'Oradea': 380,
    'Pitesti': 100,
    'Rimnicu Vilcea': 193,
    'Sibiu': 253,
    'Timisoara': 329,
    'Urziceni': 80,
    'Vaslui': 199,
    'Zerind': 374
}

# Import heapq to implement priority queue for A* (min-heap)
import heapq

# --- A* Search Function ---
def a_star_romanian(graph, start, goal, heuristic):
    # Priority queue stores tuples: (f_score, current_city, path_taken, g_score)
    queue = [(heuristic[start], start, [start], 0)]
    # Set to track visited cities
    visited = set()

    # Loop until queue is empty
    while queue:
        #print(queue)
        # Pop city with smallest f_score from priority queue
        f, current, path, g = heapq.heappop(queue)

        # If goal is reached, return path and total cost
        if current == goal:
            return path, g
        # If already visited, skip this city
        if current in visited:
            continue
        # Mark current city as visited
        visited.add(current)

        # Explore neighbors of current city
        for neighbor, cost in graph[current].items():
            # Only consider unvisited cities
            if neighbor not in visited:
                # g_new = actual cost so far + edge cost
                g_new = g + cost
                # f_new = g_new (actual cost) + heuristic(neighbor) (estimated cost to goal)
                f_new = g_new + heuristic[neighbor]
                # Push neighbor into priority queue with updated path and cost
                heapq.heappush(queue, (f_new, neighbor, path + [neighbor], g_new))

    # If no path found, return None
    return None, None

# --- Solve the problem: Find path from Arad to Bucharest ---
path, cost = a_star_romanian(graph, 'Arad', 'Bucharest', heuristic)

# --- Print the Solution ---
if path:
    # Print the sequence of cities visited
    print("Path found:", " -> ".join(path))
    # Print the total distance traveled
    print("Total distance:", cost, "km")
else:
    # Print if no path exists
    print("No path found.")